### ISSUE TITLE
Some problems about uppercase letter

### ISSUE THREAD

**Issue by ESWZY** [OverflowCat/ManchuBot#1]
Some uppercase letters are not be converted. 🤔

![image](https://user-images.githubusercontent.com/32200887/138088719-0d1e096b-2986-4b6a-9f9a-d4c3f7518f06.png)

**Comment by OverflowCat** [comment]
Sorry for not responding timely. This is by design, say `J` and `j` convert to different letters.
![IMG_20220428_093353](https://user-images.githubusercontent.com/20166026/165658597-35d72e38-f919-4f1e-8488-c4e10d7d51a0.jpg)

**Comment by ESWZY** [comment]
OK, that's great.
